// Generated by gencpp from file master_fsm/ServerListenerRequest.msg
// DO NOT EDIT!


#ifndef MASTER_FSM_MESSAGE_SERVERLISTENERREQUEST_H
#define MASTER_FSM_MESSAGE_SERVERLISTENERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace master_fsm
{
template <class ContainerAllocator>
struct ServerListenerRequest_
{
  typedef ServerListenerRequest_<ContainerAllocator> Type;

  ServerListenerRequest_()
    : command()
    , coordinate_x(0)
    , coordinate_y(0)  {
    }
  ServerListenerRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , coordinate_x(0)
    , coordinate_y(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef int32_t _coordinate_x_type;
  _coordinate_x_type coordinate_x;

   typedef int32_t _coordinate_y_type;
  _coordinate_y_type coordinate_y;





  typedef boost::shared_ptr< ::master_fsm::ServerListenerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master_fsm::ServerListenerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ServerListenerRequest_

typedef ::master_fsm::ServerListenerRequest_<std::allocator<void> > ServerListenerRequest;

typedef boost::shared_ptr< ::master_fsm::ServerListenerRequest > ServerListenerRequestPtr;
typedef boost::shared_ptr< ::master_fsm::ServerListenerRequest const> ServerListenerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master_fsm::ServerListenerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master_fsm::ServerListenerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace master_fsm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::master_fsm::ServerListenerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_fsm::ServerListenerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_fsm::ServerListenerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_fsm::ServerListenerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_fsm::ServerListenerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_fsm::ServerListenerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master_fsm::ServerListenerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a14156efaa5856a84301761fe567b3e";
  }

  static const char* value(const ::master_fsm::ServerListenerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a14156efaa5856aULL;
  static const uint64_t static_value2 = 0x84301761fe567b3eULL;
};

template<class ContainerAllocator>
struct DataType< ::master_fsm::ServerListenerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master_fsm/ServerListenerRequest";
  }

  static const char* value(const ::master_fsm::ServerListenerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master_fsm::ServerListenerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n\
int32 coordinate_x\n\
int32 coordinate_y\n\
";
  }

  static const char* value(const ::master_fsm::ServerListenerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master_fsm::ServerListenerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.coordinate_x);
      stream.next(m.coordinate_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServerListenerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master_fsm::ServerListenerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::master_fsm::ServerListenerRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "coordinate_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.coordinate_x);
    s << indent << "coordinate_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.coordinate_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_FSM_MESSAGE_SERVERLISTENERREQUEST_H
