// Generated by gencpp from file master_fsm/ServerListener.msg
// DO NOT EDIT!


#ifndef MASTER_FSM_MESSAGE_SERVERLISTENER_H
#define MASTER_FSM_MESSAGE_SERVERLISTENER_H

#include <ros/service_traits.h>


#include <master_fsm/ServerListenerRequest.h>
#include <master_fsm/ServerListenerResponse.h>


namespace master_fsm
{

struct ServerListener
{

typedef ServerListenerRequest Request;
typedef ServerListenerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServerListener
} // namespace master_fsm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_fsm::ServerListener > {
  static const char* value()
  {
    return "ecdbfcf9ee801b3b9db296d38b5364d1";
  }

  static const char* value(const ::master_fsm::ServerListener&) { return value(); }
};

template<>
struct DataType< ::master_fsm::ServerListener > {
  static const char* value()
  {
    return "master_fsm/ServerListener";
  }

  static const char* value(const ::master_fsm::ServerListener&) { return value(); }
};


// service_traits::MD5Sum< ::master_fsm::ServerListenerRequest> should match 
// service_traits::MD5Sum< ::master_fsm::ServerListener > 
template<>
struct MD5Sum< ::master_fsm::ServerListenerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_fsm::ServerListener >::value();
  }
  static const char* value(const ::master_fsm::ServerListenerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_fsm::ServerListenerRequest> should match 
// service_traits::DataType< ::master_fsm::ServerListener > 
template<>
struct DataType< ::master_fsm::ServerListenerRequest>
{
  static const char* value()
  {
    return DataType< ::master_fsm::ServerListener >::value();
  }
  static const char* value(const ::master_fsm::ServerListenerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_fsm::ServerListenerResponse> should match 
// service_traits::MD5Sum< ::master_fsm::ServerListener > 
template<>
struct MD5Sum< ::master_fsm::ServerListenerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_fsm::ServerListener >::value();
  }
  static const char* value(const ::master_fsm::ServerListenerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_fsm::ServerListenerResponse> should match 
// service_traits::DataType< ::master_fsm::ServerListener > 
template<>
struct DataType< ::master_fsm::ServerListenerResponse>
{
  static const char* value()
  {
    return DataType< ::master_fsm::ServerListener >::value();
  }
  static const char* value(const ::master_fsm::ServerListenerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_FSM_MESSAGE_SERVERLISTENER_H
