// Generated by gencpp from file driver_node/driver_setting.msg
// DO NOT EDIT!


#ifndef DRIVER_NODE_MESSAGE_DRIVER_SETTING_H
#define DRIVER_NODE_MESSAGE_DRIVER_SETTING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace driver_node
{
template <class ContainerAllocator>
struct driver_setting_
{
  typedef driver_setting_<ContainerAllocator> Type;

  driver_setting_()
    : period(0)
    , duty(0)
    , wheel(0)  {
    }
  driver_setting_(const ContainerAllocator& _alloc)
    : period(0)
    , duty(0)
    , wheel(0)  {
  (void)_alloc;
    }



   typedef int32_t _period_type;
  _period_type period;

   typedef int8_t _duty_type;
  _duty_type duty;

   typedef int8_t _wheel_type;
  _wheel_type wheel;





  typedef boost::shared_ptr< ::driver_node::driver_setting_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::driver_node::driver_setting_<ContainerAllocator> const> ConstPtr;

}; // struct driver_setting_

typedef ::driver_node::driver_setting_<std::allocator<void> > driver_setting;

typedef boost::shared_ptr< ::driver_node::driver_setting > driver_settingPtr;
typedef boost::shared_ptr< ::driver_node::driver_setting const> driver_settingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::driver_node::driver_setting_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::driver_node::driver_setting_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace driver_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'driver_node': ['/home/xillinux/cobot/catkin_ws/src/driver_node/msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::driver_node::driver_setting_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::driver_node::driver_setting_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::driver_node::driver_setting_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::driver_node::driver_setting_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::driver_node::driver_setting_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::driver_node::driver_setting_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::driver_node::driver_setting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6697fb50f4e483911cb6c8595601db97";
  }

  static const char* value(const ::driver_node::driver_setting_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6697fb50f4e48391ULL;
  static const uint64_t static_value2 = 0x1cb6c8595601db97ULL;
};

template<class ContainerAllocator>
struct DataType< ::driver_node::driver_setting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "driver_node/driver_setting";
  }

  static const char* value(const ::driver_node::driver_setting_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::driver_node::driver_setting_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 period\n\
int8 duty\n\
int8 wheel\n\
";
  }

  static const char* value(const ::driver_node::driver_setting_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::driver_node::driver_setting_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.period);
      stream.next(m.duty);
      stream.next(m.wheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct driver_setting_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::driver_node::driver_setting_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::driver_node::driver_setting_<ContainerAllocator>& v)
  {
    s << indent << "period: ";
    Printer<int32_t>::stream(s, indent + "  ", v.period);
    s << indent << "duty: ";
    Printer<int8_t>::stream(s, indent + "  ", v.duty);
    s << indent << "wheel: ";
    Printer<int8_t>::stream(s, indent + "  ", v.wheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVER_NODE_MESSAGE_DRIVER_SETTING_H
