# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from driver_node/driver_setting.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class driver_setting(genpy.Message):
  _md5sum = "6697fb50f4e483911cb6c8595601db97"
  _type = "driver_node/driver_setting"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 period
int8 duty
int8 wheel
"""
  __slots__ = ['period','duty','wheel']
  _slot_types = ['int32','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       period,duty,wheel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(driver_setting, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.period is None:
        self.period = 0
      if self.duty is None:
        self.duty = 0
      if self.wheel is None:
        self.wheel = 0
    else:
      self.period = 0
      self.duty = 0
      self.wheel = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i2b().pack(_x.period, _x.duty, _x.wheel))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.period, _x.duty, _x.wheel,) = _get_struct_i2b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i2b().pack(_x.period, _x.duty, _x.wheel))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.period, _x.duty, _x.wheel,) = _get_struct_i2b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i2b = None
def _get_struct_i2b():
    global _struct_i2b
    if _struct_i2b is None:
        _struct_i2b = struct.Struct("<i2b")
    return _struct_i2b
